### ISSUE TITLE
Not using runPendingAnimations()?

### ISSUE THREAD

**Issue by d370urn3ur** [google/android-ui-toolkit-demos#1]
Hi, thanks for the videos and this sample, it really helped me understand what is going on!  Just a quick question on the implementation: you return true from animateChange(), but never make use of runPendingAnimations(), instead you just start the animations directly in animateChange().  But reading the docs, it seems like we are supposed to be determining if we need animations and creating the animations in the animateXXX() methods, then returning true if so, then starting them in runPendingAnimations().  Am I missing something?  If we can simply start the animations directly in the animateXXX() methods, what is the purpose of runPendingAnimations()?  Thanks again!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
