### ISSUE TITLE
DataBinding example with recyclerview cannot handle shared pool

### ISSUE THREAD

**Issue by yigit** [google/android-ui-toolkit-demos#3]
The adapter in data binding examples add a callback when the ViewHolder is created but if the ViewHolder is shared between adapters, this won't work.
We should remove the listener when the ViewHolder is recycled and add it when bind is called for the first time.

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
