### ISSUE TITLE
Request to change filter icon on YouTube Android

### ISSUE THREAD

**Issue by ugreg** [google/android-ui-toolkit-demos#5]
I noticed the filter icon in the YouTube app is a settings icon. Is there some open source org I can raise this feedback too change this? Is there some way I can contribute and help replace the icon?

what the current filter icon looks like > http://imgur.com/a/vKzkP

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
