### ISSUE TITLE
Error at hide view with text 

### ISSUE THREAD

**Issue by jstr14** [google/android-ui-toolkit-demos#6]
Hello,

I'm using TransitionManager to animate some views at change visibility but I found a bug.

On my layout I have two buttons with constraint layout chain:

            <Button
                    android:text="@string/email_button"
                    android:paddingStart="16dp"
                    style="@style/seasonTextColor"
                    android:background="@drawable/round_button_background_center_info"
                    android:textAllCaps="false"
                    android:layout_width="0dp"
                    android:layout_height="44dp"
                    android:id="@+id/emailButton"
                    android:layout_marginTop="16dp"
                    app:layout_goneMarginTop="16dp"
                    app:layout_constraintTop_toBottomOf="@+id/educatorsList"
                    app:layout_constraintStart_toStartOf="parent"
                    app:layout_constraintHorizontal_chainStyle="spread_inside"
                    android:layout_marginStart="24dp"
                    app:layout_constraintHorizontal_bias="0.5"
                    app:layout_constraintEnd_toStartOf="@+id/callButton"/>

            <Button
                    android:text="@string/call_button"
                    android:background="@drawable/round_button_background_center_info_gradient"
                    android:paddingStart="16dp"
                    android:textColor="@color/white"
                    android:layout_gravity="center"
                    android:textAllCaps="false"
                    android:layout_width="0dp"
                    android:layout_height="44dp"
                    android:id="@+id/callButton"
                    app:layout_constraintTop_toTopOf="@+id/emailButton"
                    app:layout_constraintEnd_toEndOf="parent"
                    android:layout_marginEnd="24dp"
                    app:layout_constraintStart_toEndOf="@+id/emailButton"
                    app:layout_constraintHorizontal_bias="0.5"
                    android:layout_marginStart="16dp"/>

Both are inside a group to manage visibility and when I use TransitionManager to show them It works but when I use it to hide them the text inside button reduce width until only one char is visible.

My code to change visibility is:

    override fun hideCenterInfo() {
        TransitionManager.beginDelayedTransition(centerInfoContainer)
        centerInfoGroup?.visibility = View.GONE
    }

Thank you!

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
