### ISSUE TITLE
Register clicks on data in DataBoundList

### ISSUE THREAD

**Issue by cyrixmorten** [google/android-ui-toolkit-demos#7]
I have implemented DataBoundList and so far working just fine.

Only problem is that it is not clear to me how to register clicks on individual data items. 

Am new to the whole data binding in Android in general, so might have missed an obvious solution.

Thank you in advance

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location where we can accept Pull Requests (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories
